const landmarks=window.PARNAS_LANDMARKS;const monsters=window.PARNAS_MONSTERS;
let mode='landmarks',selectedLandmark=-1,selectedMonsters=[];
const map=document.querySelector('#map'),list=document.querySelector('#list'),search=document.querySelector('#search'),hint=document.querySelector('#hint'),title=document.querySelector('#sideTitle');
const label=document.createElement('div');label.className='map-label';map.append(label);const connectorSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');connectorSvg.classList.add('popup-connector');connectorSvg.setAttribute('aria-hidden','true');map.append(connectorSvg);const monsterPopup=document.createElement('section');monsterPopup.className='monster-popup';monsterPopup.hidden=true;monsterPopup.setAttribute('aria-live','polite');map.append(monsterPopup);
function pointFor(area){if(area.landmark){const p=landmarks.find(([n])=>n===area.landmark);return p?{x:p[1],y:p[2]}:null}return{x:area.x,y:area.y}}
function clearZones(){map.querySelectorAll('.spawn-zone,.spawn-name').forEach(e=>e.remove());connectorSvg.replaceChildren()}
function positionMonsterPopup(areas){monsterPopup.classList.remove('above','below');if(!areas.length){monsterPopup.style.left='14px';monsterPopup.style.top='auto';monsterPopup.style.bottom='14px';connectorSvg.replaceChildren();return}const points=areas.map(area=>({area,p:pointFor(area)})).filter(v=>v.p);if(!points.length){connectorSvg.replaceChildren();return}const w=map.clientWidth,h=map.clientHeight;monsterPopup.style.bottom='auto';monsterPopup.style.left='0px';monsterPopup.style.top='0px';const pw=monsterPopup.offsetWidth,ph=monsterPopup.offsetHeight;const centerX=points.reduce((sum,v)=>sum+v.p.x*w/100,0)/points.length;const topY=Math.min(...points.map(v=>v.p.y*h/100-v.area.r*w/100));const bottomY=Math.max(...points.map(v=>v.p.y*h/100+v.area.r*w/100));let above=topY-ph-30>=10;let top=above?topY-ph-30:bottomY+30;if(!above&&top+ph>h-10){above=true;top=topY-ph-30}top=Math.max(10,Math.min(h-ph-10,top));const left=Math.max(10,Math.min(w-pw-10,centerX-pw/2));monsterPopup.style.left=left+'px';monsterPopup.style.top=top+'px';const rect=monsterPopup.getBoundingClientRect(),mapRect=map.getBoundingClientRect(),l=rect.left-mapRect.left,t=rect.top-mapRect.top,cardW=rect.width,cardH=rect.height;connectorSvg.replaceChildren();for(const v of points){const cx=v.p.x*w/100,cy=v.p.y*h/100,r=v.area.r*w/100;let sx=Math.max(l,Math.min(l+cardW,cx)),sy=Math.max(t,Math.min(t+cardH,cy));if(cx>=l&&cx<=l+cardW&&cy>=t&&cy<=t+cardH){const edges=[{x:cx,y:t,d:cy-t},{x:cx,y:t+cardH,d:t+cardH-cy},{x:l,y:cy,d:cx-l},{x:l+cardW,y:cy,d:l+cardW-cx}].sort((a,b)=>a.d-b.d);sx=edges[0].x;sy=edges[0].y}const dx=cx-sx,dy=cy-sy,len=Math.hypot(dx,dy)||1,line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',cx-dx/len*r);line.setAttribute('y2',cy-dy/len*r);connectorSvg.append(line)}monsterPopup.classList.add(above?'above':'below')}
function renderLocationLinks(container,location){const candidates=landmarks.map(([name],index)=>[name,index]);const companyIndex=landmarks.findIndex(([name])=>name==="スティールハーツ・コンパニー");if(companyIndex>=0)candidates.push(["スティールハーツ",companyIndex]);let rest=location;while(rest){let match=null,matchAt=rest.length;for(const [name,index] of candidates){const at=rest.indexOf(name);if(at>=0&&(at<matchAt||(at===matchAt&&(!match||name.length>match[0].length)))){match=[name,index];matchAt=at}}if(!match){container.append(document.createTextNode(rest));break}if(matchAt>0)container.append(document.createTextNode(rest.slice(0,matchAt)));const link=document.createElement("button");link.type="button";link.className="landmark-link";link.textContent=match[0];link.addEventListener("click",e=>{e.stopPropagation();mode="landmarks";selectedLandmark=match[1];selectedMonsters=[];search.value="";render()});container.append(link);rest=rest.slice(matchAt+match[0].length)}}
function makeRow(name,sub,active,fn){const b=document.createElement('button');b.className='item'+(active?' active':'');const first=document.createElement('span');first.className='num';first.setAttribute('aria-hidden','true');const text=document.createElement('span');text.textContent=name;b.append(first,text);if(sub){const small=document.createElement('small');small.textContent=sub;small.style.cssText='display:block;color:#aaa797;font-size:11px';text.append(document.createElement('br'),small)}b.onclick=fn;list.append(b)}
function render(){const q=search.value.trim().toLocaleLowerCase('ja');list.replaceChildren();monsterPopup.hidden=true;monsterPopup.classList.remove('above');clearZones();document.querySelectorAll('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));
if(mode==='landmarks'){title.textContent='ランドマーク';search.placeholder='ランドマークを検索';search.setAttribute('aria-label','ランドマークを検索');hint.textContent='一覧または地図上のダイヤを選択';landmarks.forEach(([name],i)=>{if(!name.toLocaleLowerCase('ja').includes(q))return;makeRow(name,'',selectedLandmark===i,()=>{selectedLandmark=i;selectedMonsters=[];render()})});document.querySelectorAll('.pin').forEach((b,i)=>b.classList.toggle('active',i===selectedLandmark));label.style.display=selectedLandmark<0?'none':'block';if(selectedLandmark>=0){const [name,x,y]=landmarks[selectedLandmark];label.textContent=name;label.style.left=x+'%';label.style.top=y+'%'}clearZones();return}
selectedLandmark=-1;document.querySelectorAll('.pin').forEach(b=>b.classList.remove('active'));label.style.display='none';
if(mode==='monsters'){title.textContent='モンスター';search.placeholder='検索';search.setAttribute('aria-label','検索');hint.textContent='名前を選ぶと位置・収集品・生産素材・その他を表示';monsters.filter(m=>[m.name,m.location,...m.collect,...m.materials,...m.other].join(' ').toLocaleLowerCase('ja').includes(q)).forEach(m=>makeRow(m.name,'',selectedMonsters.includes(m.id),()=>{selectedMonsters=selectedMonsters[0]===m.id?[]:[m.id];render()}));const selected=monsters.find(m=>m.id===selectedMonsters[0]);if(selected){monsterPopup.hidden=false;const h=document.createElement('h3');h.textContent=selected.name;const close=document.createElement('button');close.className='popup-close';close.type='button';close.setAttribute('aria-label','閉じる');close.textContent='×';close.onclick=()=>{selectedMonsters=[];render()};const dl=document.createElement('dl');const dtLocation=document.createElement('dt');dtLocation.textContent='位置';const ddLocation=document.createElement('dd');renderLocationLinks(ddLocation,selected.location);dl.append(dtLocation,ddLocation);for(const [labelText,values] of [['収集品',selected.collect],['生産素材',selected.materials],['その他',selected.other]]){const dt=document.createElement('dt');dt.textContent=labelText;const dd=document.createElement('dd');dd.textContent=values&&values.length?values.join('、'):'未入力';dl.append(dt,dd)}monsterPopup.replaceChildren(h,close,dl);positionMonsterPopup(selected.areas);for(const area of selected.areas){const point=pointFor(area);if(!point)continue;const circle=document.createElement('div');circle.className='spawn-zone';circle.style.left=point.x+'%';circle.style.top=point.y+'%';circle.style.width=(area.r*2)+'%';circle.style.height=(area.r*2)+'%';map.append(circle)}}}
}
landmarks.forEach(([name,x,y],i)=>{const b=document.createElement('button');b.className='pin';b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label',name);b.onclick=()=>{mode='landmarks';selectedLandmark=i;selectedMonsters=[];render()};map.append(b)});
document.querySelectorAll('.mode-btn').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;selectedLandmark=-1;selectedMonsters=[];search.value='';render()}));search.addEventListener('input',()=>{render()});map.addEventListener('click',e=>{if(!e.target.closest('.pin')&&!e.target.closest('.monster-popup')&&(selectedLandmark>=0||selectedMonsters.length)){selectedLandmark=-1;selectedMonsters=[];render()}});render();